// <auto-generated />
using System;
using ControleFinanceiro.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930202014_AdicionarAberturaEConfirmacao")]
    partial class AdicionarAberturaEConfirmacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.API.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("ValorAbertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Contas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contas_Abertura", "([DataAbertura] IS NULL AND [ValorAbertura] IS NULL) OR ([DataAbertura] IS NOT NULL AND [ValorAbertura] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.RevisaoTransacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Antes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depois")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Instante")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TransacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.ToTable("RevisoesTransacoes", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.Salario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.ToTable("Salarios", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassificacaoPendente")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("ConfirmadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataEfetivacao")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DesconsideradaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NaoReconciliada");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MotivoDesconsideracao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<string>("OrigemRegistro")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TransacaoOrigemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Data");

                    b.HasIndex("MetodoPagamento");

                    b.HasIndex("Tipo");

                    b.HasIndex("TransacaoOrigemId");

                    b.HasIndex("ContaId", "Estado", "DataEfetivacao", "Id");

                    b.ToTable("Transacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transacoes_Confirmacao", "[Estado] <> 'Confirmada' OR ([ContaId] IS NOT NULL AND [DataEfetivacao] IS NOT NULL AND [ConfirmadaEm] IS NOT NULL AND [Valor] > 0 AND [MetodoPagamento] <> 'CartaoCredito' AND ([OrigemRegistro] IS NULL OR [OrigemRegistro] <> 'CreditoLegado') AND [ClassificacaoPendente] IS NULL AND [NumeroParcelas] = 1 AND [ParcelaAtual] IS NULL AND [TransacaoOrigemId] IS NULL)");
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.RevisaoTransacao", b =>
                {
                    b.HasOne("ControleFinanceiro.API.Models.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.Transacao", b =>
                {
                    b.HasOne("ControleFinanceiro.API.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.API.Models.Transacao", "TransacaoOrigem")
                        .WithMany("Parcelas")
                        .HasForeignKey("TransacaoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conta");

                    b.Navigation("TransacaoOrigem");
                });

            modelBuilder.Entity("ControleFinanceiro.API.Models.Transacao", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
